name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  android:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: 29
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.2'
          channel: 'stable'
      - run: flutter config --enable-macos-desktop
      - run: flutter doctor -v
      - run: flutter pub get
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          target: ${{ matrix.target }}
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          script: flutter test integration_test/app_test.dart
  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '2.10.2'
          architecture: x64
      - run: flutter config --enable-macos-desktop
      - run: flutter doctor -v
      - run: flutter pub get
      - uses: futureware-tech/simulator-action@v2
        with:
          model: 'iPhone 8'
      - run: flutter test integration_test/app_test.dart
